# This is a basic workflow to help you get started with Actions

name: gae-ci-cd
on:
  push:
    branches: [main]
          
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - id: 'deploy'
      uses: 'google-github-actions/deploy-appengine@v0'
      with:
        deliverables: app.yml
